# Generated by Django 4.1 on 2022-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='history_log',
            field=models.JSONField(default=list),
        ),
    ]
